name: CI

on: [ push, workflow_dispatch ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: arm64-apple-darwin, os: macos-latest   }
          - { name: x64-linux-gnu,      os: ubuntu-latest  }
          - { name: x64-windows-msvc,   os: windows-latest }

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 1

    - name: Configure
      run: cmake --preset default

    - name: Build
      run: cmake --build --preset release

    - name: Test
      run: ctest --preset release
